# Generated by Django 3.0 on 2020-07-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_nick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nick',
        ),
    ]
